### PR TITLE
Revert changes made in #3358

### LINKED ISSUE #3401: _get_scheduler() exception if dask.multiprocessing missing
These lines were recently changed in #3358 
https://github.com/pydata/xarray/blob/3f9069ba376afa35c0ca83b09a6126dd24cb8127/xarray/backends/locks.py#L87-L92

If the 'cloudpickle' package is not installed, then `dask.multiprocessing` is not available. The `try/except` that used to be wrapped around `if actual_get is dask.multiprocessing.get` meant that `_get_scheduler()` worked in that case, returning `"threaded"` (I assume this was the expected behaviour). After #3358, `_get_scheduler()` raised an `AttributeError: module 'dask' has no attribute 'multiprocessing'` until I installed 'cloudpickle'.

Suggest either reverting the changes that removed the `try/except` or making 'cloudpickle' a dependency.

--------------------------
To reproduce:
1. check 'cloudpickle' is not installed, but 'dask' is
2. execute the following commands
```
>>> import xarray
>>> xarray.backends.api._get_scheduler()
```
Expected result: `"threaded"`
Actual result:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-20da238796b7> in <module>
----> 1 xarray.backends.api._get_scheduler()

~/.local/lib/python3.6/site-packages/xarray/backends/locks.py in _get_scheduler(get, collection)
     87         pass
     88 
---> 89     if actual_get is dask.multiprocessing.get:
     90         return "multiprocessing"
     91     else:

AttributeError: module 'dask' has no attribute 'multiprocessing'
```

### PR DESCRIPTION
**Pull request by rdoyle45**
Revert changes made in #3358 which cause errors if cloudpickle is not installed.

Closes #3401

### CODE REVIEW

**Comment by crusaderky** [comment]
Tests broken by #3409 - please stand by...

**Comment by crusaderky** [comment]
Thank you
