### PR TITLE
Change np.core.defchararray to np.char (#9165)

### LINKED ISSUE #9165: testing.assert_allclose on string dtype gives error with NumPy 2.0.0
### What happened?

This error came up in an [nc2zarr](https://github.com/bcdev/nc2zarr) unit test in a nightly CI run, just after the release of NumPy 2.0.0. [This](https://github.com/bcdev/nc2zarr/blob/4841f39b40e0e4b4de47e6d297d5dacd0d4a2799/tests/test_writer.py#L312) is the test in question, and [here](https://github.com/bcdev/nc2zarr/blob/4841f39b40e0e4b4de47e6d297d5dacd0d4a2799/tests/test_writer.py#L476) is the call to `xarray.testing.allclose` which triggers the error:

```
AttributeError: Module 'numpy._core' has no attribute 'defchararray'
```

### What did you expect to happen?

We expected that `xarray.testing.allclose` would perform as stated rather than producing an error.

### Minimal Complete Verifiable Example

```Python
import numpy as np
import xarray as xr

xr.testing.assert_allclose(
    da := xr.DataArray(np.array("a", dtype="|S1")),
    da.copy()
)
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [X] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Relevant log output

```Python
Traceback (most recent call last):
  File "/home/pont/allclose_error.py", line 6, in <module>
    xr.testing.assert_allclose(
  File "/home/pont/loc/repos/xarray/xarray/testing/assertions.py", line 32, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pont/loc/repos/xarray/xarray/testing/assertions.py", line 282, in assert_allclose
    ) and compat_variable(a.variable, b.variable)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pont/loc/repos/xarray/xarray/testing/assertions.py", line 274, in compat_variable
    return a.dims == b.dims and (a._data is b._data or equiv(a.data, b.data))
                                                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pont/loc/repos/xarray/xarray/testing/assertions.py", line 45, in _data_allclose_or_equiv
    arr1 = _decode_string_data(arr1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pont/loc/repos/xarray/xarray/testing/assertions.py", line 39, in _decode_string_data
    return np.core.defchararray.decode(data, "utf-8", "replace")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/pont/mambaforge/envs/xrrepo/lib/python3.12/site-packages/numpy/core/__init__.py", line 30, in __getattr__
    attr = getattr(_core, attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pont/mambaforge/envs/xrrepo/lib/python3.12/site-packages/numpy/_core/__init__.py", line 167, in __getattr__
    raise AttributeError(f"Module {__name__!r} has no attribute {name!r}")
AttributeError: Module 'numpy._core' has no attribute 'defchararray'
```

### Anything else we need to know?

Error appears to be due to a failed import of `defchararray` from a path that's no longer valid in NumPy 2. `numpy._core.defchararray` says "The preferred alias for `defchararray` is `numpy.char`.". Replacing `np.core.defchararray` with `np.char.chararray` in `xarray.testing.assertions` seems to fix it.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:23:07) [GCC 12.3.0]
python-bits: 64
OS: Linux
OS-release: 5.15.0-107-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: ('en_GB', 'UTF-8')
libhdf5: 1.14.2
libnetcdf: 4.9.3-development

xarray: 0.1.dev5453+g872c1c5
pandas: 2.2.2
numpy: 2.0.0
scipy: 1.13.1
netCDF4: 1.7.1
pydap: None
h5netcdf: 1.3.0
h5py: 3.11.0
zarr: 2.18.2
cftime: 1.6.4
nc_time_axis: 1.4.1
iris: None
bottleneck: 1.4.0
dask: 2024.6.2
distributed: 2024.6.2
matplotlib: 3.9.0
cartopy: None
seaborn: 0.13.2
numbagg: 0.8.1
fsspec: 2024.6.0
cupy: None
pint: None
sparse: None
flox: 0.9.8
numpy_groupies: 0.11.1
setuptools: 70.1.0
pip: 24.0
conda: None
pytest: 8.2.2
mypy: 1.10.0
IPython: 8.25.0
sphinx: None
</details>

### PR DESCRIPTION
**Pull request by pont-us**
Replace a reference to np.core.defchararray with np.char.chararray in xarray.testing.assertions, since the former no longer works on NumPy 2.0.0 and the latter is the "preferred alias" according to NumPy docs. See Issue #9165.

- [x] Closes #9165
- [x] Tests added
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

### CODE REVIEW

File: xarray/testing/assertions.py [hunk 1]
```diff
@@ -36,7 +36,7 @@ def wrapper(*args, **kwargs):
 
 def _decode_string_data(data):
     if data.dtype.kind == "S":
-        return np.core.defchararray.decode(data, "utf-8", "replace")
+        return np.char.chararray.decode(data, "utf-8", "replace")
```
Comment (keewis) [inline xarray/testing/assertions.py:39]: I think we should use the function instead of the method:
```suggestion
        return np.char.decode(data, "utf-8", "replace")
```

**Review by keewis — COMMENTED** [review]
Thanks for the fix, @pont-us.

Could you also add a test to make sure we don't regress? This could be as simple as adding another parameter set to https://github.com/pydata/xarray/blob/872c1c576dc4bc1724e1c526ddc45cb420394ce3/xarray/tests/test_assertions.py#L39-L61 or https://github.com/pydata/xarray/blob/872c1c576dc4bc1724e1c526ddc45cb420394ce3/xarray/tests/test_assertions.py#L33-L36

You might also want to add a note to `whats-new.rst`

File: xarray/testing/assertions.py (hunk 1 above)
Comment (pont-us) [reply xarray/testing/assertions.py]: Good point, done!

**Comment by pont-us** [comment]
> You might also want to add a note to `whats-new.rst`

I didn't think this would qualify as a "notable" bug fix, but glad to oblige :)

File: xarray/tests/test_assertions.py [hunk 2]
```diff
@@ -52,6 +52,11 @@ def test_allclose_regression() -> None:
             xr.Dataset({"a": ("x", [0, 2]), "b": ("y", [0, 1])}),
             id="Dataset",
         ),
+        pytest.param(
+            xr.DataArray(np.array("a", dtype="|S1")),
+            xr.DataArray(np.array("b", dtype="|S1")),
+            id="DataArray_dtypeS",
```
Comment (keewis) [inline xarray/tests/test_assertions.py:58]:
```suggestion
            id="DataArray_with_character_dtype",
```

**Review by keewis — APPROVED** [review]
looks good to me, just one small nit.

File: doc/whats-new.rst [hunk 3]
```diff
@@ -35,6 +35,8 @@ Deprecations
 
 Bug fixes
 ~~~~~~~~~
+- Make `testing.assert_allclose` work with numpy 2.0 (:issue:`9165`, :pull:`9166`).
```
Comment (keewis) [inline doc/whats-new.rst:38]:
```suggestion
- Make :py:func:`testing.assert_allclose` work with numpy 2.0 (:issue:`9165`, :pull:`9166`).
```

**Comment by pont-us** [comment]
From a quick look, it appears that the failing Doctests are due to other, unrelated NumPy 2 changes (mainly [NEP 51](https://numpy.org/neps/nep-0051-scalar-representation.html)).

**Comment by keewis** [comment]
yep, this is also fails on `main`, so you can ignore these failing tests.

File: doc/whats-new.rst [hunk 4]
```diff
@@ -35,6 +35,8 @@ Deprecations
 
 Bug fixes
 ~~~~~~~~~
+- Make :py:func:`testing.assert_allclose` work with numpy 2.0 (:issue:`9165`, :pull:`9166`).
+  By `Pontus Lurcock <https://github.com/pont-us>`_
```
Comment (keewis) [inline doc/whats-new.rst:39]:
```suggestion
  By `Pontus Lurcock <https://github.com/pont-us>`_.
```

**Comment by max-sixty** [comment]
Thanks @pont-us 

(any other changes for numpy 2.0 would be greatly appreciated if you're up for it...)

**Comment by keewis** [comment]
just FYI, the doctest / rtd will be fixed by #9177, and the normal CI will be fixed by #9136 (we just need to figure out whether using `view` is a good idea). This leaves us with the `pydap` check, but since `pydap` raises an error with `numpy>=2` there's nothing we can do about other than disabling in CI and raising an issue on the `pydap` issue tracker.

**Comment by max-sixty** [comment]
That's awesome, thanks @keewis !

**Comment by pont-us** [comment]
Thanks for the help @keewis and thanks for the thanks @max-sixty :). I don't think I'll have time for another PR in the short term, unfortunately, but I plan to at least open issues for one or two other NumPy-2-related surprises that I've come across (if nobody else does first).
