### ISSUE TITLE
Cannot import xarray.tests due to use of pytest.config

### ISSUE THREAD

**Issue by jjhelmus** [pydata/xarray#1353]
xarray.tests cannot be imported due to the use of pytest.config:

```
$ python -c "import xarray; print(xarray.__version__); import xarray.tests"
0.9.2-3-g9479038
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jhelmus/devel/xarray/xarray/tests/__init__.py", line 118, in <module>
    not pytest.config.getoption("--run-flaky"),
AttributeError: module 'pytest' has no attribute 'config'
```

The use of pytest.config in the `xarray/tests/__init__.py` seem to have been introduced in #1336.  From the discussion in pytest-dev/pytest#1688 it seems as if the use of `pytest.config` is discouraged.

**Comment by jjhelmus** [comment]
pytest-dev/pytest#472 from [BitBucket #472](https://bitbucket.org/pytest-dev/pytest/issues/472) seems to touch on this topic and references the note found at the end of the [skip and xfail documentation](https://docs.pytest.org/en/latest/skipping.html):

> You cannot use pytest.config.getvalue() in code imported before pytest’s argument parsing takes place. 
> For example, conftest.py files are imported before command line parsing and thus config.getvalue() will not execute correctly.

**Comment by shoyer** [comment]
Hmm. This seems like an easy way to add a few options to running our test suite, but maybe there is a better way to do this? I guess we could hack in a fallback with `hasattr()` but that's pretty ugly.

Just out of curiosity, what reason did you have for importing `xarray.tests`?

**Comment by jjhelmus** [comment]
> Just out of curiosity, what reason did you have for importing xarray.tests?

`xarray.tests` is listed as a import test in the [conda-forge xarray-feedstock](https://github.com/conda-forge/xarray-feedstock) and was failing when I was doing a build.  I do not think that import line needs to be present, `tests` does not seem to be in the public API of xarray.  I'd be in favor of removing that line and keeping the test suite setup as-is.

**Comment by shoyer** [comment]
@jjhelmus Agreed! For testing public API, being able to import `xarray` and `xarray.backends` should be enough.

**Comment by shoyer** [comment]
@jjhelmus see conda-forge/xarray-feedstock#20

**Comment by jjhelmus** [comment]
@shoyer Agreed, there is no need for `xarray.tests` to be importable.  Closing this issue, thanks for the quick clarification.
