### ISSUE TITLE
ddof does not working with 0.10.9

### ISSUE THREAD

**Issue by fujiisoup** [pydata/xarray#2440]
Copied from issue#2236 [comments](https://github.com/pydata/xarray/pull/2236#issuecomment-424697772), by @st-bender

Hi,
just to let you know that .std() does not accept the ddof keyword anymore (it worked in 0.10.8)
Should I open a new bugreport?

Edit:
It fails with:

```python
~/Work/miniconda3/envs/stats/lib/python3.6/site-packages/xarray/core/duck_array_ops.py in f(values, axis, skipna, **kwargs)
    234 
    235         try:
--> 236             return func(values, axis=axis, **kwargs)
    237         except AttributeError:
    238             if isinstance(values, dask_array_type):

TypeError: nanstd() got an unexpected keyword argument 'ddof'
```
