### PR TITLE
Check if zarr store supports consolidated metadata

### PR DESCRIPTION
**Pull request by TomNicholas**
Needed to support the addition of `.supports_consolidated_metadata` in zarr-python upstream: https://github.com/zarr-developers/zarr-python/pull/3119.

- [ ] Closes #xxxx
- [x] Tests added
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [ ] ~~New functions/methods are listed in `api.rst`~~

### CODE REVIEW

File: xarray/tests/test_backends.py [hunk 1]
```diff
@@ -3744,6 +3746,29 @@ def test_chunk_key_encoding_v2(self) -> None:
                 assert actual["var1"].encoding["chunks"] == (2, 2)
 
 
+class NoConsolidatedMetadataSupportStore(WrapperStore[Store]):
```
Comment (TomNicholas) [inline xarray/tests/test_backends.py]: TODO: I don't think I even want to try and define this class if zarr-python v3 is not installed

File: xarray/backends/zarr.py [hunk 2]
```diff
@@ -1768,6 +1768,10 @@ def _get_open_params(
     else:
         missing_exc = zarr.errors.GroupNotFoundError
 
+    if _zarr_v3():
+        if not store.supports_consolidated_metadata:
```
Comment (jhamman) [inline xarray/backends/zarr.py]:
```suggestion
        if not getattr(store, "supports_consolidated_metadata", True):
```

I think this will be needed for Zarr >3.0.0,<3.1.0

Comment (TomNicholas) [reply xarray/backends/zarr.py]: Right - I had something like that then removed it 🤦

Comment (TomNicholas) [reply xarray/backends/zarr.py]: added in https://github.com/pydata/xarray/pull/10457/commits/a47b2e2de4b86a2a8a4844b6dc661fc1dce253be

File: xarray/tests/test_backends.py [hunk 3]
```diff
@@ -3744,6 +3749,25 @@ def test_chunk_key_encoding_v2(self) -> None:
                 assert actual["var1"].encoding["chunks"] == (2, 2)
 
 
+@requires_zarr_v3
+class TestZarrNoConsolidatedMetadataSupport(ZarrBase):
+    @contextlib.contextmanager
+    def create_zarr_target(self):
+        class NoConsolidatedMetadataSupportStore(WrapperStore[Store]):
```
Comment (TomNicholas) [inline xarray/tests/test_backends.py]: Defined `NoConsolidatedMetadataSupportStore` inside the test here because I didn't want to deal with trying to make this class definable if v3 isn't installed

**Comment by TomNicholas** [comment]
@maxrjones continuing the discussion from https://github.com/pydata/xarray/issues/10261#issuecomment-3019321183, it's not easy to implement `.with_read_only` for a `WrapperStore`. 

My `.with_read_only` implementation needs to call `__init__` (which I so far have not needed to override), and `__init__` needs to be able to reconstruct the whole class. The `read_only` kwarg should be passed down to the wrapped store, but that's already been initialized. I tried  calling the `.with_read_only` of the already-initialized wrapped store, but in this case that's a `MemoryStore`, so it's not implemented.

The store ends up looking like this, which feels like it should be part of the `WrapperStore` superclass, but it won't work in general.

```python
class NoConsolidatedMetadataSupportStore(WrapperStore[Store]):
    """
    Store that explicitly does not support consolidated metadata.

    Useful as a proxy for stores like Icechunk, see https://github.com/zarr-developers/zarr-python/pull/3119.
    """

    supports_consolidated_metadata = False

    def __init__(
        self,
        store: Store,
        *,
        read_only: bool = False,
    ) -> None:
        self._store = store.with_read_only(read_only=read_only)

    def with_read_only(self, read_only: bool = False) -> NoConsolidatedMetadataSupportStore:
        return type(self)(
            store=self._store,
            read_only=read_only,
        )
```

The core problem is that `.with_read_only` needs to know all the information needed to re-initialise the same store, so now my store (and potentially all stores?) have to carry all that state around with it at all times.

(Also why exactly does a `MemoryStore` not implement `.with_read_only`?)

**Comment by d-v-b** [comment]
> The core problem is that .with_read_only needs to know all the information needed to re-initialise the same store, so now my store (and potentially all stores?) have to carry all that state around with it at all times.

IMO the solution to this problem is for each store to have a method that returns a dict of the parameters needed to create the store. I think we have this _implicitly_ via `__getstate__`., but I think it would be good to make it a public method. These dicts could then be statically typed, and eventually the dict itself could be provided instead of a class instance to top-level APIs that expect a store. If such dicts were JSON-serializable they could also be used for interchange, to share store configurations.

**Comment by d-v-b** [comment]
Instead of adding new API, we could also make all the stores dataclasses, and then you could use `dataclasses.asdict` on them to generate the dict of parameters.

**Comment by TomNicholas** [comment]
> IMO the solution to this problem is for each store to have a method that returns a dict of the parameters needed to create the store.

This all assumes that a store is cheap to create. Is that always true? It feels like a massive change to zarr to now suddenly require that all stores carry around all information needed to recreate them, and to create many copies of them under normal use.

**Comment by maxrjones** [comment]
> Also why exactly does a MemoryStore not implement .with_read_only?

It does - https://github.com/zarr-developers/zarr-python/blob/baabf08d07e8518e3d37bd83c493a1d46ea7ac1d/src/zarr/storage/_memory.py#L57-L62. I think I just skipped ZipStore because file locking makes it a bit more complicated.

**Comment by TomNicholas** [comment]
> > Also why exactly does a MemoryStore not implement .with_read_only?
>
> It does

Oh sorry my bad - `uv` was using the wrong version of zarr. I think I made this work now, but my concerns about the size of this change remain.

**Comment by maxrjones** [comment]
> > IMO the solution to this problem is for each store to have a method that returns a dict of the parameters needed to create the store.
> 
> This all assumes that a store is cheap to create. Is that always true? It feels like a massive change to zarr to now suddenly require that all stores carry around all information needed to recreate them, and to create many copies of them under normal use.

I don't think this is actually a big change because this is already how pickling works when using Zarr for distributed computing. It's just whether to encourage this pattern for other use-cases.

**Comment by paraseba** [comment]
> This all assumes that a store is cheap to create. Is that always true?

I share this concern. Particularly because it's not entirely clear how the new and old store instances will be used. Should both remain perfectly valid? In general instantiating a new Store may be expensive. There could be caches, connection pools, etc. Should all those be shared among the two instances that are alive after using `with_read_only`?

Having to know how to create new instances, seems a quite heavyweight mechanism to deal with a read only flag. As @TomNicholas also mentions, wrapping stores also become more complex.

**Comment by paraseba** [comment]
> I don't think this is actually a big change because this is already how pickling works when using Zarr for distributed computing

Supporting the distributed use case in Icechunk is quite complex, and it depends heavily on knowing the pickled Stores are part of the same "write session"

**Comment by maxrjones** [comment]
It's not possible to maintain backwards compatibility and require a new method on all Zarr stores. Therefore, any new method such as a public version of `__getstate__` would be optional, as is `with_read_only()`. Therefore, the assumption is that "a copy of *some* stores are cheap to create" rather than the broader assumption that "a store is cheap to create". I think this assumption is valid. You can manually create writeable and readable stores for your wrapper store rather than using the `with_read_only()` convenience method if the store is not cheap to create and you don't want to support `with_read_only()`.

**Comment by d-v-b** [comment]
> In general instantiating a new Store may be expensive. There could be caches, connection pools, etc. Should all those be shared among the two instances that are alive after using with_read_only?

Associating a new store instance to an old connection pool or cache is not in principle expensive, within a single process. And if we _do_ want to share these resources, then IMO the best approach is to define those resources as part of the store's data model, but with optionality semantics, because in general sharing in-memory resources across separate processes is hard or impossible.

More broadly, I think it's really attractive to declare e.g. cloud storage as a piece of data that can be shared, and used by multiple clients to instantiate the "same" store. This is only practical if the data model of the store allows it. For cloud stores, the data model does generally allow a declarative store model. For "i need a live connection to a consumable resource" stores like `ZipStore`, a declarative model is harder. But IMO we should lean more declarative wherever possible.

**Comment by paraseba** [comment]
@maxrjones what are the consequences if Icechunk decides not to implement the new method? How does Zarr interpret this?

**Comment by maxrjones** [comment]
> @maxrjones what are the consequences if Icechunk decides not to implement the new method? How does Zarr interpret this?

If a user tries to open a group or array with a mode of `r` using an Icechunk store with `read_only` set to `False`, they will receive a `ValueError` similar to the following:

```
Exception has occurred: ValueError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
Store is not read-only but mode is 'r'. Unable to create a read-only copy of the store.
  File "/Users/max/Documents/Code/zarr-developers/zarr-python/src/zarr/storage/_common.py", line 126, in open
    # writable store and writable mode
  File "/Users/max/Documents/Code/zarr-developers/zarr-python/src/zarr/abc/store.py", line 103, in with_read_only
        f"with_read_only is not implemented for the {type(self)} store type."
    
    )
NotImplementedError: with_read_only is not implemented for the <class 'zarr.storage._zip.ZipStore'> store type.

The above exception was the direct cause of the following exception:

  File "/Users/max/Documents/Code/zarr-developers/zarr-python/src/zarr/storage/_common.py", line 128, in open
    
    
    # Handle mode-specific operations
  File "/Users/max/Documents/Code/zarr-developers/zarr-python/src/zarr/storage/_common.py", line 373, in make_store_path
    return result
    
  File "/Users/max/Documents/Code/zarr-developers/zarr-python/src/zarr/api/asynchronous.py", line 1262, in open_array
    store_path = await make_store_path(store, path=path, mode=mode, storage_options=storage_options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/max/Documents/Code/zarr-developers/zarr-python/src/zarr/core/sync.py", line 119, in _runner
    return await coro
           ^^^^^^^^^^
  File "/Users/max/Documents/Code/zarr-developers/zarr-python/src/zarr/core/sync.py", line 163, in sync
    raise return_result
  File "/Users/max/Documents/Code/zarr-developers/zarr-python/src/zarr/api/synchronous.py", line 1297, in open_array
            async_api.open_array(
            ^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
                storage_options=storage_options,
    
  File "/Users/max/Documents/Code/zarr-developers/zarr-python/.vscode/test-zip-mode.py", line 5, in <module>
    arr = zarr.open_array(store=store, path="a", zarr_format=2, mode="r")
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/runpy.py", line 198, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
ValueError: Store is not read-only but mode is 'r'. Unable to create a read-only copy of the store.
```

Alternatives that were considered:
- Making the Store's read_only attribute mutable (bad idea because stores are shared across arrays and in general mutable properties are discouraged)
- Separating the permissions model of groups, stores, and arrays. The general sentiment is that this is a good idea and take away the need for the above error and therefore any consequences for Icechunk. But it was decided that `with_read_only()` was an appropriate compromise between convenience and safety as a fix for https://github.com/zarr-developers/zarr-python/issues/3147. While more granular permissions will hopefully provide a more robust long-term solution, the `with_read_only()` convenience method on stores could still be helpful for testing infrastructure so isn't a complete waste IMO.
- Raising an error any time a user tries to open an array/group with mode="r" on a non-read-only store for all Store sub-classes. This was deemed too disruptive for users (e.g., 200+ xarray failures).

**Comment by paraseba** [comment]
Thank you @maxrjones . Long term, I'd love to see the responsibility for managing the readonly flag removed from the abstract `Store` hierarchy. It feels this is a concern that is beyond what a `Store` should know about. It would help us keeping the Stores abstract and focused. Readonly-ness sounds like a session concern, independent of the details of how to write zarr objects to different media.

**Comment by TomNicholas** [comment]
Thanks for the discussion everyone - I want to move any further discussion of this over to https://github.com/zarr-developers/zarr-python/issues/3186, where I've raised @paraseba's suggestion as an issue.

For now I think I have what I need to be able to finish this PR.

**Comment by TomNicholas** [comment]
So for this PR obviously there are [failures](https://github.com/pydata/xarray/actions/runs/16007948546/job/45158864384?pr=10457) here, but:
- [ ] Upstream includes unreleased zarr data types changes, which will break a lot of things until @ianhi 's PR #10456 goes in - these are not needed for compatibility with zarr `3.0.9`
- [x] Most of the failures are easy to fix (things like regexes getting differently-worded error messages than they expected) EDIT: Apparently @dcherian already fixed this one in `main` in https://github.com/pydata/xarray/pull/10485, tracked by https://github.com/pydata/xarray/issues/10486
- [x] I think the `AttributeError: Can't get local object 'TestZarrNoConsolidatedMetadataSupport.create_zarr_target.<locals>.NoConsolidatedMetadataSupportStore'` were caused by me hiding the definition of my test store in the test itself, and don't indicate a real bug EDIT: Defining it inside caused it to be unpickleable, which breaks some of the tests
- [x] There are still `Store is not read-only but mode is 'r'`, for tests where we use `ZipStore`, because IIUC that does not implement `.with_read_only`. As this is a breaking change the only way to work around it would be to change xarray's tests to use a read-only zip store, and that should technically be done in a separate PR to this one. EDIT: See https://github.com/zarr-developers/zarr-python/issues/3194 and the temporary workaround https://github.com/pydata/xarray/issues/10486
- [x] There is a failure where reading a non-consolidated store does not warn when it's expected to warn - I think that does indicate a logic bug in this PR for me to fix EDIT: addressed in https://github.com/pydata/xarray/pull/10457/commits/101b28074ea10d46e12d46d18758abc9e80ecfe7, the test was expecting a warning that doesn't makes sense to be thrown for a store which does not support consolidated metadata

But that's it - then xarray should work with zarr `3.0.9` (and icechunk).

File: xarray/tests/test_backends.py (hunk 3 above)
Comment (TomNicholas) [reply xarray/tests/test_backends.py]: Actually this breaks the pickling tests

**Comment by TomNicholas** [comment]
- [x] There is also an significant upstream performance regression caught by tests here that I am trying to ignore in https://github.com/pydata/xarray/pull/10491

**Review by rabernat — APPROVED** [review]

**Review by paraseba — APPROVED** [review]
