### PR TITLE
ndrolling repr fix

### LINKED ISSUE #4328: failing docs CI
The RTD builds are timing out again. With my own [setup](https://readthedocs.org/projects/xarray-keewis/builds/11623675/) I get this error instead:

<details><summary>Traceback</summary>

```pytb
AttributeError                            Traceback (most recent call last)
~/checkouts/readthedocs.org/user_builds/xarray-keewis/conda/latest/lib/python3.8/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/checkouts/readthedocs.org/user_builds/xarray-keewis/conda/latest/lib/python3.8/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

~/checkouts/readthedocs.org/user_builds/xarray-keewis/conda/latest/lib/python3.8/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

~/checkouts/readthedocs.org/user_builds/xarray-keewis/checkouts/latest/xarray/core/rolling.py in __repr__(self)
     99         """provide a nice str repr of our rolling object"""
    100 
--> 101         attrs = [
    102             "{k}->{v}".format(k=k, v=getattr(self, k))
    103             for k in list(self.dim) + self.window + self.center + [self.min_periods]

~/checkouts/readthedocs.org/user_builds/xarray-keewis/checkouts/latest/xarray/core/rolling.py in <listcomp>(.0)
    100 
    101         attrs = [
--> 102             "{k}->{v}".format(k=k, v=getattr(self, k))
    103             for k in list(self.dim) + self.window + self.center + [self.min_periods]
    104         ]

AttributeError: 'DataArrayRolling' object has no attribute 'y'
```

</details>

I think that was introduced in #4219. cc @fujiisoup

Also, we should definitely ask support why those two behave differently. Edit: see readthedocs/readthedocs.org#7371

### PR DESCRIPTION
**Pull request by fujiisoup**
- [x] Closes #4328
 - [x] Tests added
 - [x] Passes `isort . && black . && mypy . && flake8`

There was a bug in `rolling.__repr__` but it was not tested.
Fixed and tests are added.

### CODE REVIEW

File: xarray/tests/test_dataarray.py [hunk 1]
```diff
@@ -6178,6 +6178,8 @@ def test_rolling_iter(da):
                 actual.values[actual.values.nonzero()],
                 expected.values[expected.values.nonzero()],
             )
+    # no error
+    repr(rolling_obj)
```
Comment (keewis) [inline xarray/tests/test_dataarray.py:6182]: could you move this to its own test? That way this test cannot be shadowed by a failure in the code above

**Comment by keewis** [comment]
This looks good to me, but unfortunately, this uncovered a separate issue, triggered by https://github.com/pydata/xarray/blob/7e1fbf87b898851d26de3eb3ab328637d61437bc/doc/computation.rst#L234-L239


<details><summary>Traceback</summary>

```pytb
ValueError                                Traceback (most recent call last)
<ipython-input-38-e6e456ecd183> in <module>
----> 1 rolling_da = r.construct("window_dim", stride=2)

.../xarray/core/rolling.py in construct(self, window_dim, stride, fill_value, **window_dim_kwargs)
    277             window_dim = {d: window_dim_kwargs[d] for d in self.dim}
    278 
--> 279         window_dim = self._mapping_to_list(
    280             window_dim, allow_default=False, allow_allsame=False
    281         )

.../xarray/core/rolling.py in _mapping_to_list(self, arg, default, allow_default, allow_allsame)
    157             return [arg]
    158         else:
--> 159             raise ValueError("Mapping argument is necessary.")
    160 
    161 

ValueError: Mapping argument is necessary.
```

</details>

**Comment by fujiisoup** [comment]
Thanks @keewis for checking.
I'm not sure what causes the error in `rolling_da.mean("window_dim", skipna=False) `

`self._mapping_to_list` should handle this problem. 
How can I get the details of this error?
I just saw the time-out error...

**Comment by keewis** [comment]
normally you'd look at the output of the RTD build, but somehow just that specific build fails so I put in a support request on RTD. I can reproduce the failure using:
```python
In [1]: import xarray as xr 
   ...: import numpy as np 
   ...:  
   ...: arr = xr.DataArray(np.arange(0, 7.5, 0.5).reshape(3, 5), dims=("x", "y")) 
   ...: display(arr) 
   ...: r = arr.rolling(x=2, y=3, min_periods=2) 
   ...: display(r) 
   ...:  
   ...: rolling_da = r.construct("window_dim", stride=2) 
   ...: display(rolling_da)
<xarray.DataArray (x: 3, y: 5)>
array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ]])
Dimensions without coordinates: x, y
DataArrayRolling [x->2,y->3]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-f9a10c0cfaeb> in <module>
      7 display(r)
      8 
----> 9 rolling_da = r.construct("window_dim", stride=2)
     10 display(rolling_da)
     11 rolling_da.mean("window_dim", skipna=False)

.../xarray/core/rolling.py in construct(self, window_dim, stride, fill_value, **window_dim_kwargs)
    277             window_dim = {d: window_dim_kwargs[d] for d in self.dim}
    278 
--> 279         window_dim = self._mapping_to_list(
    280             window_dim, allow_default=False, allow_allsame=False
    281         )

.../xarray/core/rolling.py in _mapping_to_list(self, arg, default, allow_default, allow_allsame)
    157             return [arg]
    158         else:
--> 159             raise ValueError("Mapping argument is necessary.")
    160 
    161 

ValueError: Mapping argument is necessary.
```
so the bug is in `Rolling.construct`.

**Comment by fujiisoup** [comment]
Thanks, @keewis , for the clarification.

It was a bug in the documentation page but not in `rolling.construct`.

It should raise an error in this case, because for 2d rolling we need 2 dimension names,
```python
rolling_da = r.construct(x="x_win", y='y_win' , stride=2) 
```
I corrected the documentation and error message.

File: doc/computation.rst [hunk 2]
```diff
@@ -234,7 +234,7 @@ windowed rolling, convolution, short-time FFT etc.
 .. ipython:: python
 
     # rolling with 2-point stride
-    rolling_da = r.construct("window_dim", stride=2)
+    rolling_da = r.construct(x="x_win", y="y_win", stride=2)
     rolling_da
     rolling_da.mean("window_dim", skipna=False)
```
Comment (keewis) [inline doc/computation.rst:239]: we need something like
```suggestion
    rolling_da.mean(["x_win", "y_win"], skipna=False)
```
otherwise the docs will still fail

**Comment by keewis** [comment]
thanks, that fixed the build on my own RTD setup, but the main setup is quite a bit slower...

**Comment by keewis** [comment]
all CI passes. Thanks for the quick fixes, @fujiisoup
