### PR TITLE
Re-enable tests xfailed in #3808 and fix new CFTimeIndex failures due to upstream changes

### PR DESCRIPTION
**Pull request by spencerkclark**
xref: #3869

### CODE REVIEW

**Comment by spencerkclark** [comment]
Hmm...the upstream-dev CI environment does not seem to be using the latest version of pandas.  The failures don't seem to reflect the fact that https://github.com/pandas-dev/pandas/pull/32684 was merged.

Testing locally with pandas master, I'm actually getting some new failures related to CFTimeIndex, e.g.:
```
_______________________________________ test_concat_cftimeindex[proleptic_gregorian] ________________________________________

date_type = <class 'cftime._cftime.DatetimeProlepticGregorian'>

    @requires_cftime
    def test_concat_cftimeindex(date_type):
        da1 = xr.DataArray(
>           [1.0, 2.0], coords=[[date_type(1, 1, 1), date_type(1, 2, 1)]], dims=["time"]
        )

test_cftimeindex.py:670:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../core/dataarray.py:344: in __init__
    coords, dims = _infer_coords_and_dims(data.shape, coords, dims)
../core/dataarray.py:165: in _infer_coords_and_dims
    assert_unique_multiindex_level_names(new_coords)
../core/variable.py:2390: in assert_unique_multiindex_level_names
    idx_level_names = var.to_index_variable().level_names
../core/variable.py:2252: in level_names
    index = self.to_index()
../core/variable.py:2244: in to_index
    index = index.set_names(self.name)
../../../pandas/pandas/core/indexes/base.py:1291: in set_names
    idx = self._shallow_copy()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = CFTimeIndex([0001-01-01 00:00:00, 0001-02-01 00:00:00], dtype='object'), values = None, name = None

    def _shallow_copy(self, values=None, name: Label = no_default):
        """
        Create a new Index with the same class as the caller, don't copy the
        data, use the same object attributes with passed in attributes taking
        precedence.

        *this is an internal non-public method*

        Parameters
        ----------
        values : the values to create the new Index, optional
        name : Label, defaults to self.name
        """
        name = self.name if name is no_default else name
>       cache = self._cache.copy() if values is None else {}
E       AttributeError: 'CFTimeIndex' object has no attribute '_cache'

../../../pandas/pandas/core/indexes/base.py:500: AttributeError
```

**Comment by spencerkclark** [comment]
5f37fd4 fixes the additional failures I described in https://github.com/pydata/xarray/pull/3874#issuecomment-602044048.  They seem to be related to https://github.com/pandas-dev/pandas/pull/32568.  @jbrockmendel, does that seem like the correct fix to you?

**Comment by dcherian** [comment]
> the upstream-dev CI environment does not seem to be using the latest version of pandas.

There's something about wheels needing to be updated.

Here's how we install it.
https://github.com/pydata/xarray/blob/5354679579d46d3bcb620817125c5bde3c4f1cff/ci/azure/install.yml#L15-L23

**Comment by dcherian** [comment]
Thanks @spencerkclark
