### ISSUE TITLE
xarray 0.13.0 crashes mypy type checker

### ISSUE THREAD

**Issue by scivision** [pydata/xarray#3341]
I have many xarray-based projects that all are regularly checked with MyPy / CI.
This worked normally until xarray 0.13.0, which crashes mypy 0.701..0.720 at least.

#### MWE

create file foo.py containing merely
```python
import xarray
```

then
```sh
mypy foo.py
```

results in

```
C:\Miniconda3\lib\site-packages\xarray\core\dataarray.py:1858: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.701      
C:\Miniconda3\lib\site-packages\xarray\core\dataarray.py:1858: : note: please use --show-traceback to print a traceback when reporting a bug
```

#### workaround

The workaround was to include in my project's mypy.ini:

```ini
[mypy-xarray]
follow_imports = skip
```

**Comment by max-sixty** [comment]
Could you show versions as per the issue template? This works on mypy 0.720 on mine: ` echo "import xarray" > foo.py && mypy foo.py`

**Comment by shoyer** [comment]
Also, the stacktrace (as suggested in the error message) could probably be informative here.

**Comment by crusaderky** [comment]
This happened to me on a completely different project. It is typically triggered by a mypy version upgrade /downgrade. ``rm - rf .mypy_cache`` fixed it for me.

**Comment by dcherian** [comment]
closing since this might not be an xarray issue. feel free to reopen if necessary.
