### PR TITLE
Support Pydap 3.2, including on Python 3

### LINKED ISSUE #1174: pydap support is broken for recent releases of pydap (and on Python 3)
Hello!

I was hoping to spend some of my end-of-the-year free time picking up low-hanging fruits in xarray, and while trying to clean up tests failures as mentioned in #1109, I've come across an issue using `engine='pydap'`.

Specifically, I can't get `engine='pydap'` to work at all:

```
>>> import xarray

;; opening with default backend works ('netcdf4' I think?)
>>> xarray.open_dataset("http://test.opendap.org/opendap/hyrax/data/nc/123bears.nc")
<xarray.Dataset>
Dimensions:...
Coordinates:...
Data variables:...
Attributes:...

;; but using 'pydap'...
>>> xarray.open_dataset("http://test.opendap.org/opendap/hyrax/data/nc/123bears.nc", engine='pydap')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "xarray/backends/api.py", line 306, in open_dataset
    return maybe_decode_store(store, lock)
  File "xarray/backends/api.py", line 227, in maybe_decode_store
    drop_variables=drop_variables)
  File "xarray/conventions.py", line 941, in decode_cf
    vars, attrs = obj.load()
  File "xarray/backends/common.py", line 100, in load
    for k, v in iteritems(self.get_variables()))
  File "xarray/backends/pydap_.py", line 72, in get_variables
    for k, v in self.ds.iteritems())
  File "/Users/daniel.lee/anaconda/envs/test_env/lib/python2.7/site-packages/pydap/model.py", line 301, in __getattr__
    return DapType.__getattr__(self, attr)
  File "/Users/daniel.lee/anaconda/envs/test_env/lib/python2.7/site-packages/pydap/model.py", line 188, in __getattr__
    % (self.__class__, attr))
AttributeError: '<class 'pydap.model.DatasetType'>' object has no attribute 'iteritems'
```
latest xarray + latest pydap (3.2.0)

From my best attempt at looking over the `xarray` code and playing with `pydap.client`, I'm beginning to suspect that `engine='pydap'` no longer working in xarray (for instance - as noted in the exception msg above - you cannot call `iteritems()` on `pydap.model.DatasetType` but `xarray` insists on doing so).

Is what I'm seeing and suggesting correct? If so, is xarray still committed to supporting `pydap` as an engine (and be a worthwhile things for a new contributors to work on)?

### PR DESCRIPTION
**Pull request by shoyer**
- [x] Closes #1174
 - [x] Tests added / passed
 - [x] Passes ``git diff upstream/master | flake8 --diff``
 - [x] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API

I also verified that this solution works on Pydap 3.1 (with Python 2.7).

### CODE REVIEW

**Comment by shoyer** [comment]
Thanks @laliberte for doing the hard work that made this possible!

File: ci/requirements-py36.yml [hunk 1]
```diff
@@ -18,3 +18,4 @@ dependencies:
   - pip:
     - coveralls
     - pytest-cov
+    - pydap
```
Comment (fmaussion) [inline ci/requirements-py36.yml]: Is there a reason for testing pydap on py3.6 only?

Comment (shoyer) [inline ci/requirements-py36.yml]: Our pydap tests are currently network only tests, and we only run those on Python 3.6.
