### ISSUE TITLE
failing docs CI

### ISSUE THREAD

**Issue by keewis** [pydata/xarray#4328]
The RTD builds are timing out again. With my own [setup](https://readthedocs.org/projects/xarray-keewis/builds/11623675/) I get this error instead:

<details><summary>Traceback</summary>

```pytb
AttributeError                            Traceback (most recent call last)
~/checkouts/readthedocs.org/user_builds/xarray-keewis/conda/latest/lib/python3.8/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/checkouts/readthedocs.org/user_builds/xarray-keewis/conda/latest/lib/python3.8/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

~/checkouts/readthedocs.org/user_builds/xarray-keewis/conda/latest/lib/python3.8/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

~/checkouts/readthedocs.org/user_builds/xarray-keewis/checkouts/latest/xarray/core/rolling.py in __repr__(self)
     99         """provide a nice str repr of our rolling object"""
    100 
--> 101         attrs = [
    102             "{k}->{v}".format(k=k, v=getattr(self, k))
    103             for k in list(self.dim) + self.window + self.center + [self.min_periods]

~/checkouts/readthedocs.org/user_builds/xarray-keewis/checkouts/latest/xarray/core/rolling.py in <listcomp>(.0)
    100 
    101         attrs = [
--> 102             "{k}->{v}".format(k=k, v=getattr(self, k))
    103             for k in list(self.dim) + self.window + self.center + [self.min_periods]
    104         ]

AttributeError: 'DataArrayRolling' object has no attribute 'y'
```

</details>

I think that was introduced in #4219. cc @fujiisoup

Also, we should definitely ask support why those two behave differently. Edit: see readthedocs/readthedocs.org#7371

**Comment by fujiisoup** [comment]
Ah, this
```
attrs = [
--> 102             "{k}->{v}".format(k=k, v=getattr(self, k))
    103             for k in list(self.dim) + self.window + self.center + [self.min_periods]
    104         ]
```
should be `"{k}->{v}".format(k=k, v=getattr(self.dims, k))` not `"{k}->{v}".format(k=k, v=getattr(self, k))`
I'll send a fix.
