### PR TITLE
Support keyword API for `Dataset.drop`

### PR DESCRIPTION
**Pull request by gwgundersen**
- Closes https://github.com/pydata/xarray/issues/2910.
- In `tests/test_dataset`, added `test_drop_labels_by_keyword`
- Added a utility function `is_list_like`.
- Documented in `whats-new.rst` and confirmed API docs built correctly.

### CODE REVIEW

**Comment by shoyer** [comment]
Awesome, thanks for working on this @gwgundersen !

In the long term, we might want to deprecate the current function signature, but I'm happy to leave that for later.

File: xarray/core/dataset.py [hunk 1]
```diff
@@ -3150,11 +3150,25 @@ def drop(self, labels, dim=None, *, errors='raise'):
...
             dataset are dropped and no error is raised.
+        **dim_kwargs : {dim: label, ...}, optional
+            The keyword arguments form of ``dim`` and ``labels``.
+            Either ``dim`` and ``labels`` or ``dim_kwargs`` must be provided.
 
         Returns
         -------
         dropped : Dataset
         """
+        if len(dim_kwargs) > 0:
```
Comment (shoyer) [inline xarray/core/dataset.py]: Just using a dict directly in a condition is the preferred way to check if it's empty:
```suggestion
        if dim_kwargs:
```

File: xarray/core/dataset.py [hunk 2]
```diff
@@ -3150,11 +3150,25 @@ def drop(self, labels, dim=None, *, errors='raise'):
             any of the variable or index labels passed are not
             in the dataset. If 'ignore', any given labels that are in the
             dataset are dropped and no error is raised.
+        **dim_kwargs : {dim: label, ...}, optional
```
Comment (shoyer) [inline xarray/core/dataset.py]: Everywhere else in xarray where we support keyword arguments, we try to use the `xarray.core.utils. either_dict_or_kwargs()` helper function, to allow writing either `dataset.method({k: v})` or `dataset.method(k=v)` inter-changeably.

It would be nice to do the same here, if possible, though it get a little bit tricky due to the need to support the original signature. I think something like this would work:
```python
if dim_kwargs or utils.is_dict_like(labels):
    dim_kwargs = utils.either_dict_or_kwargs(labels, dim_kwargs, 'drop')
    if dim is not None:
        raise ValueError(...)
    ...
```

File: xarray/core/dataset.py [hunk 3]
```diff
@@ -3150,11 +3150,25 @@ def drop(self, labels, dim=None, *, errors='raise'):
...
+            The keyword arguments form of ``dim`` and ``labels``.
+            Either ``dim`` and ``labels`` or ``dim_kwargs`` must be provided.
 
         Returns
         -------
         dropped : Dataset
```
Comment (shoyer) [inline xarray/core/dataset.py]: I would be awesome if you're up for adding a few examples here inline in the docstring.

File: xarray/core/dataset.py [hunk 4]
```diff
@@ -3150,11 +3150,25 @@ def drop(self, labels, dim=None, *, errors='raise'):
...
         """
+        if len(dim_kwargs) > 0:
+            if labels is not None or dim is not None:
+                raise ValueError('cannot specify both `dim` and `labels` along'
+                                 'with keyword arguments')
+            if len(dim_kwargs) > 1:
+                raise ValueError('cannot specify multiple dimensions')
+            dim = list(dim_kwargs.keys())[0]
+            labels = list(dim_kwargs.values())
+            if utils.is_list_like(labels[0]):
```
Comment (shoyer) [inline xarray/core/dataset.py]: I don't think we need this check -- we already handle both scalars and lists in the logic below.

Comment (gwgundersen) [reply xarray/core/dataset.py]: Since we convert `dim_kwargs`'s values to a list, if the user passes in a list, we get a list with a single element which is also a list. The logic below won't catch this list-in-list scenario. Happy to change this if you know a simpler way to handle `dict_values`. My problem was

```python
>>> x = {'foo': 1}
>>> x.values()
dict_values([1])
>>> x.values()[0] # TypeError
```

which is why I do `list(x.values())` instead.

File: xarray/core/dataset.py (hunk 2 above)
Comment (gwgundersen) [reply xarray/core/dataset.py]: Isn't `labels` supposed to be `list`-like, not `dict`-like? That is why I did not try to use `either_dict_or_kwargs`.

File: xarray/core/dataset.py (hunk 3 above)
Comment (gwgundersen) [reply xarray/core/dataset.py]: Good idea. Done.

File: xarray/core/dataset.py (hunk 4 above)
Comment (shoyer) [reply xarray/core/dataset.py]: Ah, yes. I think the cleanest way to do this would be with tuple unpacking, e.g.,
```
((dim, labels),) = dim_kwargs.items()
```
or
```
(dim, labels) = list(dim_kwargs.items())[0]
```

File: xarray/core/dataset.py (hunk 2 above)
Comment (shoyer) [reply xarray/core/dataset.py]: I'm proposing allowing labels to be *either* `list`-like or `dict`-like.

Though perhaps that's more confusing...

File: xarray/core/dataset.py (hunk 4 above)
Comment (gwgundersen) [reply xarray/core/dataset.py]: That works great. Thanks.

File: xarray/core/dataset.py (hunk 2 above)
Comment (gwgundersen) [reply xarray/core/dataset.py]: Ah, I see. This means we would also want to support the user dropping labels along multiple dimensions? The docstring would be complicated. You also mentioned above that "we might want to deprecate the current function signature", but the `dict`-like approach does not allow `dim=None`. This means we would need to support four different ways of calling the function:

- `labels` is `list`-like but no `dim`: drop variables.
- `labels` is `list`-like and `dim`: drop labels along `dim`.
- `labels` is a `dict`: drop values for each `dim` key along that dimension.
- `labels_kwargs` are used: drop values for each `dim` keyword argument.

As a first-time contributor, I don't think this is my call, but I'd vote for deprecating the "drop variables" approach in favor of `dict`-like long-term to be more consistent with other functions.

Maybe we add a new function for dropping variables or an argument `variables`?

Comment (dcherian) [reply xarray/core/dataset.py]: In the long term, can we deprecate 
> labels is list-like and dim: drop labels along dim.

and then have 3 modes of operation? i.e. when `labels` is list-like, they must be variable names.

Comment (gwgundersen) [reply xarray/core/dataset.py]: Do you think that's more clear for a user than `drop(..., variables=True)`? IMO explicit is better than implicit, and conditioning on the type of the input seems confusing, especially when that input type was previously valid. In the worst case, this would fail silently by dropping variables when a user meant dimensions.

Comment (gwgundersen) [reply xarray/core/dataset.py]: Sorry, wrote a confused reply. Yeah, I like your idea. Shall I implement?

Comment (shoyer) [reply xarray/core/dataset.py]: > In the long term, can we deprecate
> 
> > labels is list-like and dim: drop labels along dim.
> 
> and then have 3 modes of operation? i.e. when `labels` is list-like, they must be variable names.

I think this would be make sense. We'll need to support this through a deprecation cycle, but eventually we can remove it.

**Comment by max-sixty** [comment]
@gwgundersen I see you trying to merge re the recent black changes. Here are the instructions for making this (relatively) seamless: https://github.com/pydata/xarray/blob/d3f1ced1aa84cb0a0f3e47e7ee67492e203fcce5/doc/contributing.rst#code-formatting

**Comment by gwgundersen** [comment]
@max-sixty, thanks! It's useful to be able to do in advance.

After merging from master, I get this error:

```
flake8
./xarray/core/dataset.py:3466:5: F811 redefinition of unused 'drop' from line 3460
```

I assume this is due to https://github.com/pydata/xarray/pull/3177 cc @crusaderky. Is there a way to avoid this?

**Comment by max-sixty** [comment]
@gwgundersen Could you force-push your latest code? 

If your current latest code is pushed, you may have to `git reset --hard` and start again - unfortunately it looks like your PR is proposing ` +24,439 −17,647 ` changes

**Comment by gwgundersen** [comment]
Sorry about that. I'm not sure what happened. I've reverted branch and cherry picked my changes. The issue with `drop` being a duplicated name still stands.

File: xarray/core/dataset.py [hunk 5]
```diff
@@ -3463,7 +3463,7 @@ def drop(
     ) -> "Dataset":
         ...
 
-    def drop(self, labels, dim=None, *, errors="raise"):  # noqa: F811
+    def drop(self, labels=None, dim=None, *, errors="raise", **labels_kwargs):
```
Comment (max-sixty) [inline xarray/core/dataset.py]:
```suggestion
    def drop(self, labels=None, dim=None, *, errors="raise", **labels_kwargs):  # noqa: F811
```

**Comment by max-sixty** [comment]
Thanks @gwgundersen - good idea re the cherry pick for more discrete changes. 

Still getting a test failure though, check it out and lmk if you need any help

File: xarray/core/dataset.py (hunk 5 above)
Comment (max-sixty) [reply xarray/core/dataset.py]: Hopefully this doesn't break black - may need to ensure the `noqa` is in the right place if black reformats

File: xarray/core/dataset.py (hunk 2 above)
Comment (gwgundersen) [reply xarray/core/dataset.py]: Great. I followed another bit of code that just used `warnings.warn` with a `DeprecationWarning`.

File: xarray/core/dataset.py (hunk 5 above)
Comment (gwgundersen) [reply xarray/core/dataset.py]: Thanks. I had to move this comment slightly after using `black`, but it worked.

**Comment by gwgundersen** [comment]
Now the docs don't build. When I try to build locally, I get a vague error:

```bash
  File "/Users/gwg/miniconda3/envs/xarray-docs/lib/python3.7/site-packages/IPython/sphinxext/ipython_directive.py", line 583, in process_input
    raise RuntimeError('Non Expected warning in `{}` line {}'.format(filename, lineno))
RuntimeError: Non Expected warning in `/Users/gwg/projects/xarray/doc/indexing.rst` line 241
```

Do you see anything wrong with this?

```rest
The :py:meth:`~xarray.Dataset.drop` method returns a new object with the listed
index labels along a dimension dropped:

.. ipython:: python

    ds.drop(['IN', 'IL'], dim='space')
<-- line 241
``drop`` is both a ``Dataset`` and ``DataArray`` method.

Use :py:meth:`~xarray.Dataset.drop_dims` to drop a full dimension from a Dataset.
Any variables with these dimensions are also dropped:
```

**Comment by dcherian** [comment]
It looks like you've added a warming for this case. So you'll need to specify :okwarning: .

**Comment by max-sixty** [comment]
I see the docs timing out after 60 min. I also see that message, but is that causing the failure?

I restarted the docs build to see whether that might help

**Comment by gwgundersen** [comment]
Sorry for the back-and-forth. CI tests and checks are all passing, and this is ready for another review.

File: xarray/core/dataset.py [hunk 6]
```diff
@@ -3479,34 +3482,75 @@ def drop(self, labels, dim=None, *, errors="raise"):  # noqa: F811
...
         """
         if errors not in ["raise", "ignore"]:
             raise ValueError('errors must be either "raise" or "ignore"')
 
-        if dim is None:
+        labels_are_coords = isinstance(labels, DataArrayCoordinates)
+        if labels_kwargs or (utils.is_dict_like(labels) and not labels_are_coords):
+            labels_kwargs = utils.either_dict_or_kwargs(labels, labels_kwargs, "drop")
+            if dim is not None:
+                raise ValueError("cannot specify dim amd dict-like " "arguments.")
```
Comment (max-sixty) [inline xarray/core/dataset.py]:
```suggestion
                raise ValueError("cannot specify dim and dict-like arguments.")
```

**Comment by max-sixty** [comment]
@gwgundersen could we add a whatsnew too?

**Comment by gwgundersen** [comment]
@max-sixty, done.

**Comment by max-sixty** [comment]
Great @gwgundersen !

File: xarray/core/dataset.py [hunk 7]
```diff
@@ -3479,34 +3482,75 @@ def drop(self, labels, dim=None, *, errors="raise"):  # noqa: F811
...
+        Dimensions without coordinates: x
+        Data variables:
+            A        (x, y) float64 -0.3944 -1.418 1.423 -1.041
         """
         if errors not in ["raise", "ignore"]:
             raise ValueError('errors must be either "raise" or "ignore"')
 
-        if dim is None:
+        labels_are_coords = isinstance(labels, DataArrayCoordinates)
+        if labels_kwargs or (utils.is_dict_like(labels) and not labels_are_coords):
```
Comment (shoyer) [inline xarray/core/dataset.py]: I wonder if it would be more predictable to special case the `dict` type rather than `not labels_are_coords`, which is  just one of many internal xarray mapping types, e.g.,
```suggestion
        if labels_kwargs or isinstance(labels, dict):
```

More generally, I get that writing `array.drop(array.coords)` is convenient, but in the long term it seems like a bad idea to treat different mapping types differently. This suggests that such uses should be deprecated. Either `array.drop_vars(array.coords)` or `array.drop(list(array.coords))` would be less ambiguous.

File: doc/indexing.rst [hunk 8]
```diff
@@ -236,6 +236,7 @@ The :py:meth:`~xarray.Dataset.drop` method returns a new object with the listed
 index labels along a dimension dropped:
 
 .. ipython:: python
+    :okwarning:
 
     ds.drop(['IN', 'IL'], dim='space')
```
Comment (shoyer) [inline doc/indexing.rst]: Since this is deprecated, we should fix the docs to use `ds.drop(space=['IN', 'IL']` as an example of the preferred syntax going forward.

**Comment by max-sixty** [comment]
@shoyer thanks for the follow-up comments. I probably should have spotted those myself. 
But given there'll be points I miss, lmk if I should be waiting longer / raising specific points before hitting the big green button, or these post-merge reviews are OK. I can ensure they're complete before a release.

**Comment by shoyer** [comment]
Post merge reviews are totally fine. It is not a big deal to revert a merge if needed.

**Comment by gwgundersen** [comment]
Happy to make these changes, but what's the protocol here? Seems like reverting the merge and letting me amend is cleaner than me creating a new PR.

File: xarray/core/dataset.py (hunk 7 above)
Comment (gwgundersen) [reply xarray/core/dataset.py]: Yeah, I thought needing the check for `labels_are_coords` was odd, but I didn't expect passing in coordinates to take a separate code path. Special-casing the `dict` type makes sense. And the API that is being deprecated is treating `DataArrayCoordinates` as non-dict-like, right?

**Comment by shoyer** [comment]
My (limited) understanding of how github handles reverting is that you'll still need to make a new pull request to apply your edits either way. There is no more going to back to amend after PR is  merges. The only difference is what the state of "master" looks like when you make your new pull request (whether it  includes your partial changes or not).

So I don't think it particularly matters if you revert first  (as long as the forward fix happens relatively  soon), but if you'd prefer to do it that way that's totally fine -- let me know and I will do it.

File: xarray/core/dataset.py (hunk 7 above)
Comment (shoyer) [reply xarray/core/dataset.py]: > And the API that is being deprecated is treating `DataArrayCoordinates` as non-dict-like, right?

That's right, we would rather *always* use this  new rule for dict-like inputs.

**Comment by max-sixty** [comment]
I think the easiest way forward is to do a follow-up PR, no need to revert.

Reverting would be helpful if we wanted to _undo_ these changes - in this case we have some v marginal additional changes.
