### ISSUE TITLE
import_metadata==5.0.0 causes error when loading netcdf file

### ISSUE THREAD

**Issue by EtienneCmb** [pydata/xarray#7115]
### What happened?

Loading an *.nc* file under Python 3.7 and with the latest [importlib_metadata](https://github.com/python/importlib_metadata)==5.0.0 doesn't work.

### What did you expect to happen?

File should be loaded.

### Minimal Complete Verifiable Example

```Python
# Python version 3.7
# import_metadata==5.0.0

import xarray as xr
import numpy as np

data = xr.DataArray(
    np.random.rand(10, 20)
)
data.to_netcdf('test.nc')
xr.load_dataarray('test.nc')
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
Traceback (most recent call last):
  File "xarray_bug.py", line 7, in <module>
    xr.load_dataarray('test.nc')
  File "/home/etienne/anaconda3/envs/py37/lib/python3.7/site-packages/xarray/backends/api.py", line 267, in load_dataarray
    with open_dataarray(filename_or_obj, **kwargs) as da:
  File "/home/etienne/anaconda3/envs/py37/lib/python3.7/site-packages/xarray/backends/api.py", line 666, in open_dataarray
    **kwargs,
  File "/home/etienne/anaconda3/envs/py37/lib/python3.7/site-packages/xarray/backends/api.py", line 479, in open_dataset
    engine = plugins.guess_engine(filename_or_obj)
  File "/home/etienne/anaconda3/envs/py37/lib/python3.7/site-packages/xarray/backends/plugins.py", line 110, in guess_engine
    engines = list_engines()
  File "/home/etienne/anaconda3/envs/py37/lib/python3.7/site-packages/xarray/backends/plugins.py", line 105, in list_engines
    entrypoints = entry_points().get("xarray.backends", ())
AttributeError: 'EntryPoints' object has no attribute 'get'
```

### Anything else we need to know?

- Only with **importlib_metadata==5.0.0**
- Doesn't works with Python **3.7** but it works with **3.9**
- Similar problem for [flake8](https://github.com/python/importlib_metadata/issues/406) repo.
- They solved it by imposing a specific version for python versions under 3.8 : https://github.com/PyCQA/flake8/blob/2c1bfa1f3d85e4d94ebc3b6d601d454a09d8043e/setup.cfg#L44

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) 
[GCC 9.4.0]
python-bits: 64
OS: Linux
OS-release: 5.4.210-1-MANJARO
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: fr_FR.UTF-8
LOCALE: ('fr_FR', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: 4.9.0

xarray: 0.20.2
pandas: 1.3.5
numpy: 1.21.6
scipy: None
netCDF4: 1.6.1
pydap: None
h5netcdf: 1.0.2
h5py: 3.7.0
Nio: None
zarr: None
cftime: 1.6.2
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: None
cartopy: None
seaborn: None
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
setuptools: 65.4.1
pip: 22.2.2
conda: None
pytest: None
IPython: 7.34.0
sphinx: None

</details>

**Comment by Illviljan** [comment]
Hello, this should be fixed already, see: 
https://github.com/pydata/xarray/blob/f5884a2070fb6cdaa9f187cfe56c3670cfad2f87/xarray/backends/plugins.py#L101-L105

We follow [nep-29](https://numpy.org/neps/nep-0029-deprecation_policy.html) and intend to only support python >=3.8:
https://github.com/pydata/xarray/blob/f5884a2070fb6cdaa9f187cfe56c3670cfad2f87/setup.cfg#L72-L76

**Comment by EtienneCmb** [comment]
Ok, thank you. I need to update my env then :)

**Comment by Illviljan** [comment]
If you want to investigate more, feel free to try with python 3.8 as well. 
Our CI seems to install `  importlib-metadata         4.11.4        py310hff52083_0          conda-forge` for python 3.8 so maybe there's an issue there?

**Comment by dcherian** [comment]
> I need to update my env then

Thanks @EtienneCmb

**Comment by observingClouds** [comment]
I was about to open the same issue but can confirm that I only get an issue with `python<3.8` and `importlib_metadata==5.0.0`
@Illviljan , `importlib-metadata` should not be necessary for python>=3.8 as it became part of the standard library.
