### PR TITLE
Switch to T_DataArray in .coords

### PR DESCRIPTION
**Pull request by Illviljan**
- [ ] Closes #xxxx
- [ ] Tests added
- [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [ ] New functions/methods are listed in `api.rst`

### CODE REVIEW

File: xarray/core/coordinates.py [hunk 1]
```diff
@@ -341,9 +343,11 @@ class DataArrayCoordinates(Coordinates):
     dimensions and the values given by corresponding DataArray objects.
     """
 
+    _data: T_DataArray
+
     __slots__ = ("_data",)
 
-    def __init__(self, dataarray: DataArray):
+    def __init__(self, dataarray: T_DataArray):
```
Comment (headtr1ck) [inline xarray/core/coordinates.py:350]: I think you need to make the class generic as well. Not sure how this works when inheriting from Coords which is a generic `Mapping[Hashable, T_DataArray]`.

File: xarray/core/coordinates.py [hunk 2]
```diff
@@ -366,7 +369,7 @@ def dtypes(self) -> Frozen[Hashable, np.dtype]:
     def _names(self) -> set[Hashable]:
         return set(self._data._coords)
 
-    def __getitem__(self, key: Hashable) -> DataArray:
+    def __getitem__(self, key: Hashable) -> T_DataArray:
         return self._data._getitem_coord(key)
```
Comment (Illviljan) [inline xarray/core/coordinates.py:373]:
```python
xarray/core/coordinates.py:372: error: A function returning TypeVar should receive at least one argument containing the same Typevar  [type-var]
xarray/core/coordinates.py:372: note: Consider using the upper bound "DataArray" instead
```
I don't really understand this error, why should the method have at least one argument with the same TypeVar? The TypeVar is stored in self already.

Comment (headtr1ck) [reply xarray/core/coordinates.py:373]: That's what I meant with making coordinates a generic class.

Comment (Illviljan) [reply xarray/core/coordinates.py:373]: Sorry, I'm not following. Feel free to push to this PR or link me to an example you think is similar.

Comment (headtr1ck) [reply xarray/core/coordinates.py:377]: done :)

Comment (headtr1ck) [reply xarray/core/coordinates.py:377]: Ok, nvmd. This does not seem to work in python 3.8....
Anyone has an idea how to solve this? haha.

Comment (Illviljan) [reply xarray/core/coordinates.py:377]: I've been googleing without much luck. :(

One super ugly way is to just do a gigantic `if sys.version_info >= (3, 9)` check switching between the new and old version.

Comment (headtr1ck) [reply xarray/core/coordinates.py:377]: Yes, it is extremely difficult to Google python version dependent stuff...

Comment (headtr1ck) [reply xarray/core/coordinates.py:383]: Wow that is an interesting hack, haha

Comment (Illviljan) [reply xarray/core/coordinates.py:383]: Yeah, a little surprised it worked. :D

Taken from:
https://github.com/python/cpython/blob/b0e1f9c241cd8f8c864d51059217f997d3b792bf/Lib/_collections_abc.py#L428

Comment (headtr1ck) [reply xarray/core/coordinates.py:383]: Does it work though? What does a `reveal_type(da.coords)` give?
Or a `reveal_type(da.coords["x"])`?

**Comment by Illviljan** [comment]
Mypy errors with python 3.8. Doesn't appear related to this PR at least.

```
Run python -m mypy --install-types --non-interactive --cobertura-xml-report mypy_report
  python -m mypy --install-types --non-interactive --cobertura-xml-report mypy_report
  shell: /usr/bin/bash -l {0}
  env:
    CONDA_ENV_FILE: ci/requirements/environment.yml
    PYTHON_VERSION: 3.8
    TODAY: 2022-11-20
    MAMBA_ROOT_PREFIX: /home/runner/micromamba-root
    MAMBA_EXE: /home/runner/micromamba-bin/micromamba
Collecting types-PyYAML
  Downloading types_PyYAML-6.0.12.2-py3-none-any.whl (14 kB)
Collecting types-paramiko
  Downloading types_paramiko-2.12.0.1-py3-none-any.whl (32 kB)
Collecting types-pytz
  Downloading types_pytz-2022.6.0.1-py3-none-any.whl (4.7 kB)
Collecting types-setuptools
  Downloading types_setuptools-65.6.0.0-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 kB 19.4 MB/s eta 0:00:00
Collecting types-cryptography
  Downloading types_cryptography-3.3.23.2-py3-none-any.whl (30 kB)
Installing collected packages: types-setuptools, types-PyYAML, types-pytz, types-cryptography, types-paramiko
Successfully installed types-PyYAML-6.0.12.2 types-cryptography-3.3.23.2 types-paramiko-2.12.0.1 types-pytz-2022.6.0.1 types-setuptools-65.6.0.0
xarray/core/types.py:73: error: "tuple" is not subscriptable  [misc]
Generated Cobertura report: /home/runner/work/xarray/xarray/mypy_report/cobertura.xml
Installing missing stub packages:
/home/runner/micromamba-root/envs/xarray-tests/bin/python -m pip install types-PyYAML types-paramiko types-pytz types-setuptools

xarray/core/types.py:75: error: "tuple" is not subscriptable  [misc]
xarray/core/types.py:77: error: "tuple" is not subscriptable  [misc]
xarray/core/types.py:79: error: "list" is not subscriptable  [misc]
xarray/core/merge.py:43: error: "tuple" is not subscriptable  [misc]
xarray/core/merge.py:44: error: "tuple" is not subscriptable  [misc]
xarray/core/merge.py:45: error: "tuple" is not subscriptable  [misc]
xarray/backends/api.py:65: error: "dict" is not subscriptable  [misc]

Generated Cobertura report: /home/runner/work/xarray/xarray/mypy_report/cobertura.xml
Found 8 errors in 3 files (checked 140 source files)
```

**Comment by headtr1ck** [comment]
See https://github.com/pydata/xarray/pull/6963 for python 3.8

File: xarray/core/coordinates.py (hunk 2 above)
Comment (Illviljan) [reply xarray/core/coordinates.py:383]: I get this on main:
```python
da = xr.DataArray()
reveal_type(da)  # note: Revealed type is "Any"
```

Do you as well?

Comment (headtr1ck) [reply xarray/core/coordinates.py:383]: No, I get `note: Revealed type is "xarray.core.dataarray.DataArray"` as expected.

Comment (Illviljan) [reply xarray/core/coordinates.py:383]: Hmm, I use:
```
mypy                      0.982           py310h8d17308_0    conda-forge
mypy_extensions           0.4.3           py310h5588dad_5    conda-forge
...
python                    3.10.6          h9a09f29_0_cpython    conda-forge
```

**Review by headtr1ck — APPROVED** [review]
