### PR TITLE
remove outdated type-ignores

### PR DESCRIPTION
**Pull request by kmuehlbauer**
- [ ] Closes #xxxx
- [ ] Tests added
- [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [ ] New functions/methods are listed in `api.rst`

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
Those typing issues are a real pain.

So the typing worked in an environment with numpy 2.0.2. It failed with numpy 2.1.3. When removing that type-ignore it resurfaces for numpy dev version. Weird.

- numpy: 2.1.3
```python
xarray/core/dataset.py:9144: error: Unused "type: ignore" comment  [unused-ignore]
```

- numpy: 2.3.0.dev0+git20250128.a1fa8e1
```python 
xarray/core/dataset.py: note: In member "polyfit" of class "Dataset":
xarray/core/dataset.py:9144: error: Incompatible types in assignment (expression has type "floating[Any]", variable has type "float | None")  [assignment]
```

**Review by max-sixty — APPROVED** [review]
