### ISSUE TITLE
 xarray.core.groupby.DataArrayGroupBy.argmax

### ISSUE THREAD

**Issue by Hoeze** [pydata/xarray#4476]
Please implement

**Is your feature request related to a problem? Please describe.**
Observed:
```python
da.groupby("g").argmax(dim="t")
```
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-84-15c199b0f7d4> in <module>
----> 1 da.groupby("g").argmax(dim="t")

AttributeError: 'DataArrayGroupBy' object has no attribute 'argmax'
```

**Describe the solution you'd like**
Expected: Vector of length `len(unique(g))` containing the indices of `da["t"]` where the value was maximum.

**Comment by markusritschel** [comment]
This was definitely possible in the last versions (at least in v.0.15.1). Can we make this available again?

**Comment by zxdawn** [comment]
@markusritschel I tested v0.17.0 and it doesn't work.

```
data = np.random.rand(4, 3)
locs = ["IA", "IL", "IN"]
times = pd.date_range("2000-01-01", periods=4)
foo = xr.DataArray(data, coords=[times, locs], dims=["time", "space"])
foo.groupby('space').argmax('time')
```

Error: `AttributeError: 'DataArrayGroupBy' object has no attribute 'argmax'`

**Comment by markusritschel** [comment]
@zxdawn I am pretty sure it was possible in v0.15.1. But I would need to check that again.

**Comment by sjvrijn** [comment]
Using `git bisect` and @zxdawn's example, I've narrowed it down to commit bdcfab524e.

I'm guessing the exact culprit is the removal of `argmin` and `argmax` from `NAN_REDUCE_METHODS` in [xarray/core/ops.py](https://github.com/pydata/xarray/commit/bdcfab524ef1c852abe6dabcfabc7292f058fddc#diff-53544e03ec0ceff497591f986820b2fb55cbccf5c35fb02c090b291b8628cb44L50) because dedicated implementations were added for Variable/DataSet/DataArray.

**Comment by emanuelegent** [comment]
Hi I would just like to add that having the argmax functionality would make possible to extract timestamp of maximum values, such as daily maximum values. Current resample in xarray doesn't allow that
