### PR TITLE
WIP: type annotations

### LINKED ISSUE #2869: xarray.concat docstring confuses PyCharm type detection
PyCharm inspects docstrings to figure out the return type of functions. In the case of xarray.concat(), it believes it is 'type'; this causes it to prominently highlight the user code as an error:

pycharm

### PR DESCRIPTION
**Pull request by crusaderky**
Fixes #2869

### CODE REVIEW

File: xarray/core/common.py [hunk 1]
```diff
@@ -115,7 +120,15 @@ def __iter__(self):
     def T(self):
         return self.transpose()
 
-    def get_axis_num(self, dim):
+    @overload
+    def get_axis_num(self, dim: str) -> int:
+        pass
+
+    @overload  # noqa:F811
+    def get_axis_num(self, dim: Iterable[str]) -> Tuple[int]:
```
Comment (shoyer) [inline xarray/core/common.py]: Dimensions are actually allowed to be non-strings, so it might be better to keep this overload more generic, given that that reflects how the code actually works:
```suggestion
    def get_axis_num(self, dim: Iterable[Hashable]) -> Tuple[int, ...]:
```

(Also `Tuple[int]`  should be `Tuple[int, ...]`)

File: xarray/core/common.py [hunk 2]
```diff
@@ -115,7 +120,15 @@ def __iter__(self):
     def T(self):
         return self.transpose()
 
-    def get_axis_num(self, dim):
+    @overload
+    def get_axis_num(self, dim: str) -> int:
+        pass
```
Comment (shoyer) [inline xarray/core/common.py]: I think it's more idiomatic to use `...` rather than `pass` when writing overloads?

File: xarray/core/common.py [hunk 3]
```diff
@@ -133,15 +146,15 @@ def get_axis_num(self, dim):
         else:
             return tuple(self._get_axis_num(d) for d in dim)
 
-    def _get_axis_num(self, dim):
+    def _get_axis_num(self, dim: str) -> int:
```
Comment (shoyer) [inline xarray/core/common.py]:
```suggestion
    def _get_axis_num(self, dim: Hashable) -> int:
```

File: xarray/core/common.py [hunk 4]
```diff
@@ -133,15 +146,15 @@ def get_axis_num(self, dim):
...
         try:
             return self.dims.index(dim)
         except ValueError:
             raise ValueError("%r not found in array dimensions %r" %
                              (dim, self.dims))
 
     @property
-    def sizes(self):
+    def sizes(self) -> Frozen[str, int]:
```
Comment (shoyer) [inline xarray/core/common.py]: I don't think `Frozen` is a valid type annotation. Maybe better to stick with `Mapping[str, int]`?

File: xarray/core/common.py [hunk 5]
```diff
@@ -214,36 +227,38 @@ def _ipython_key_completions_(self):
         return list(set(item_lists))
 
 
-def get_squeeze_dims(xarray_obj, dim, axis=None):
+def get_squeeze_dims(xarray_obj, dim: Union[str, Tuple[str, ...], None] = None,
```
Comment (shoyer) [inline xarray/core/common.py]: Probably should be something more relaxed, perhaps `dim: Union[Hashable, Iterable[Hashable]]`

File: xarray/core/common.py [hunk 6]
```diff
@@ -271,7 +286,7 @@ def squeeze(self, dim=None, drop=False, axis=None):
         dims = get_squeeze_dims(self, dim, axis)
         return self.isel(drop=drop, **{d: 0 for d in dims})
 
-    def get_index(self, key):
+    def get_index(self, key: str) -> pd.Index:
```
Comment (shoyer) [inline xarray/core/common.py]: `key` can actually be any hashable item here.

File: xarray/core/common.py (hunk 1 above)
Comment (crusaderky) [reply xarray/core/common.py]: If they were intended to be allowed to be non-strings, sure they aren't tested for it!
```
>>> xarray.DataArray([1,2], dims=[123])
TypeError: dimension 123 is not a string
```
Also I've never seen it mentioned in the documentation...

File: xarray/core/common.py (hunk 4 above)
Comment (crusaderky) [reply xarray/core/common.py]: it is valid as I changed the Frozen class to be a subclass of typing.Mapping

File: xarray/core/common.py (hunk 5 above)
Comment (crusaderky) [reply xarray/core/common.py]: trouble with Iterable is that it doesn't necessarily allow you to iterate upon it twice (e.g. a file handler). I've tweaked the code to allow for it.

**Comment by crusaderky** [comment]
@shoyer how do you feel about raising the minimum Python version to 3.5.2? There's quite a bit of important stuff in it, some of which undocumented. Namely ``@overload`` doesn't work with 3.5.0 (although I could conditionally replace it with a no-op thorough a backport module).

**Comment by crusaderky** [comment]
From the 3.5.2 release notes:

> A new version of typing.py provides several new classes and features: @overload outside stubs, Reversible, DefaultDict, Text, ContextManager, Type[], NewType(), TYPE_CHECKING, and numerous bug fixes (note that some of the new features are not yet implemented in mypy or other static analyzers). Also classes for PEP 492 (Awaitable, AsyncIterable, AsyncIterator) have been added (in fact they made it into 3.5.1 but were never mentioned).

**Comment by crusaderky** [comment]
@shoyer I am using mypy. But unlike flake8 I don't think I'll be able to integrate it in CI.
This error doesn't make any sense to me:
```
xarray/core/common.py:124: error: Overloaded function signatures 1 and 2 overlap with incompatible return types
```

These I think are unfixable in Python 3.5, as I can't declare these under the class definition:
```
xarray/core/utils.py:445: error: "NdimSizeLenMixin" has no attribute "shape"
xarray/core/utils.py:450: error: "NdimSizeLenMixin" has no attribute "shape"
xarray/core/utils.py:454: error: "NdimSizeLenMixin" has no attribute "shape"
xarray/core/utils.py:468: error: "NDArrayMixin" has no attribute "array"
xarray/core/utils.py:472: error: "NDArrayMixin" has no attribute "array"
xarray/core/utils.py:478: error: "NDArrayMixin" has no attribute "array"
xarray/core/common.py:151: error: "AbstractArray" has no attribute "dims"
xarray/core/common.py:154: error: "AbstractArray" has no attribute "dims"
xarray/core/common.py:166: error: "AbstractArray" has no attribute "dims"
xarray/core/common.py:166: error: "AbstractArray" has no attribute "shape"
xarray/core/common.py:896: error: Cannot determine type of '_file_obj'
xarray/core/common.py:897: error: Cannot determine type of '_file_obj'
```
(additionally, typing doesn't offer anything for "file-like" objects)

**Comment by crusaderky** [comment]
Mmh it looks like if I run mypy in Python 3.7 I get a *much* terser output. Still some horrible broken things to care about, like the fact that in 3.5 ``typing.Mapping`` did not inherit from ``collections.abc.Mapping``, but they can be worked around somehow.

**Comment by crusaderky** [comment]
@shoyer I have a problem.
In Python 3.5.0-3.5.2, to create a custom typed collection you have to write
```
class Frozen(collections.abc.Mapping, typing.Mapping[K, V]):
```
Whereas in Python >= 3.5.3, you must just write
```
class Frozen(typing.Mapping[K, V]):
```
Things won't work if you use the < 3.5.3 syntax.

As an unrelated note, I'm observing that if I set python=3.5.3 in ``ci/requirements-py35.yml``, a ton of unit tests fall apart. The test suite ``ci/requirements-py35-min.yml`` ensures compatibility with Python 3.5.0... but only as long as you don't use any of the non-mandatory dependencies.
Can we 1) increase the minimum requirements to 3.5.4 and 2) set python=3.5.4 in ``ci/requirements-py35.yml``?
Is there a roadmap for dropping 3.5 entirely? (conda-forge already did...)

File: xarray/core/common.py (hunk 2 above)
Comment (crusaderky) [reply xarray/core/common.py]: fixed

File: xarray/core/common.py (hunk 1 above)
Comment (crusaderky) [reply xarray/core/common.py]: fixed ``Tuple[int, ...]``

File: xarray/core/common.py (hunk 4 above)
Comment (crusaderky) [reply xarray/core/common.py]: changed to ``Mapping[str, int]`` for the sake of user friendliness, as Frozen isn't really part of the public API

**Comment by crusaderky** [comment]
Opened https://bugs.python.org/issue36555

File: xarray/core/common.py (hunk 1 above)
Comment (shoyer) [reply xarray/core/common.py]: Hmm. It seems that you can only construct these sorts of names/dimensions with the Dataset API:
```
In [8]: xarray.Dataset({123: ((456,), [1, 2, 3])})
Out[8]:
<xarray.Dataset>
Dimensions:  (456: 3)
Dimensions without coordinates: 456
Data variables:
    123      (456) int64 1 2 3
```

**Comment by max-sixty** [comment]
FYI we added some code here to deal with python 3.5.0-3.5.2: https://github.com/pydata/xarray/pull/2831

**Comment by shoyer** [comment]
If it's not too much trouble, I'd like to keep the xarray (with type checking) working on Python 3.5.0 for now. The type checks themselves only need to work on Python 3.7.

This should be relatively straightforward if you put type annotations in strings as needed and guard typing imports in `if TYPE_CHECKING` blocks.

**Comment by crusaderky** [comment]
@shoyer I changed dimensions from str to Hashable as requested. In my opinion however it's not great, because
1. it's currently thoroughly broken due to lack of unit tests
2. it weakens type checking a lot, since Tuple is a subclass of Hashable however the vast majority of xarray functions deal with tuples with a specific code branch

Please review again - in theory, common.py and util.py are now 100% done. They pass flake8 and mypy (on python 3.7). If you like them please go on and merge into Master; since the work that needs to be done is going to touch literally everything I think it's best to break it down into more manageable chunks.

File: xarray/core/utils.py [hunk 7]
```diff
@@ -266,7 +292,10 @@ def dict_equiv(first, second, compat=equivalent):
     return True
 
 
-def ordered_dict_intersection(first_dict, second_dict, compat=equivalent):
+def ordered_dict_intersection(first_dict: Mapping[K, V],
+                              second_dict: Mapping[K, V],
+                              compat: Callable[[V, V], bool] = equivalent
+                              ) -> MutableMapping[K, V]:
```
Comment (shoyer) [inline xarray/core/utils.py]: This should probably be `'OrderedDict[K, V]'`

File: xarray/core/utils.py [hunk 8]
```diff
@@ -290,172 +319,130 @@ def ordered_dict_intersection(first_dict, second_dict, compat=equivalent):
...
     """A simple ordered set.
 
     The API matches the builtin set, but it preserves insertion order of
     elements, like an OrderedDict.
     """
-
-    def __init__(self, values=None):
-        self._ordered_dict = OrderedDict()
+    def __init__(self, values: Optional[AbstractSet[T]] = None) -> None:
+        self._ordered_dict = OrderedDict()  # type: MutableMapping[T, None]
```
Comment (shoyer) [inline xarray/core/utils.py]: You can use `type: OrderedDict[T, None]`

File: xarray/core/utils.py [hunk 9]
```diff
@@ -290,172 +319,130 @@ def ordered_dict_intersection(first_dict, second_dict, compat=equivalent):
...
         if values is not None:
-            self |= values
+            self.__ior__(values)
```
Comment (shoyer) [inline xarray/core/utils.py]: Does mypy not recognize `|=` as valid? That's usually preferred since that's the operator `__ior__` corresponds to.

If not, that's OK but please leave a comment.

File: xarray/core/utils.py [hunk 10]
```diff
@@ -290,172 +319,130 @@ def ordered_dict_intersection(first_dict, second_dict, compat=equivalent):
...
-    def discard(self, value):
+    def discard(self, value: T) -> None:
         del self._ordered_dict[value]
 
     # Additional methods
 
-    def update(self, values):
-        self |= values
+    def update(self, values: AbstractSet[T]) -> None:
+        self.__ior__(values)
```
Comment (shoyer) [inline xarray/core/utils.py]: same as above

File: xarray/core/utils.py [hunk 11]
```diff
@@ -470,27 +457,27 @@ class NDArrayMixin(NdimSizeLenMixin):
...
 
 
-class ReprObject(object):
-    """Object that prints as the given value, for use with sentinel values."""
-
-    def __init__(self, value: str):
+class ReprObject:
+    """Object that prints as the given value, for use with sentinel values.
+    """
+    def __init__(self, value: str) -> None:
```
Comment (shoyer) [inline xarray/core/utils.py]: note: I think mypy is OK with skipping `-> None` for `__init__` methods.

File: xarray/core/common.py [hunk 12]
```diff
@@ -590,8 +602,11 @@ def rolling(self, dim=None, min_periods=None, center=False, **dim_kwargs):
         return self._rolling_cls(self, dim, min_periods=min_periods,
                                  center=center)
 
-    def coarsen(self, dim=None, boundary='exact', side='left',
-                coord_func='mean', **dim_kwargs):
+    def coarsen(self, dim: Optional[Mapping[Hashable, int]] = None,
+                boundary: str = 'exact',
+                side: Union[str, Mapping[Hashable, str]] = 'left',
+                coord_func: str = 'mean',
```
[the remark this answers is not in the document]
Comment (crusaderky) [reply xarray/core/common.py]: didn't you say that all dims should be Hashable?

File: xarray/core/utils.py (hunk 7 above)
Comment (crusaderky) [reply xarray/core/utils.py]: That's painful to achieve, because typing.OrderedDict was added in python 3.7.2, and I'm scared of hacking about what is such a fundamental class for xarray.
Also, are there any methods that OrderedDict offers that MutableMapping doesn't?

Comment (shoyer) [reply xarray/core/utils.py]: If you put it in quotes, it's only checked when running mypy. That seems to work without any hacking, e.g., see 
https://github.com/pydata/xarray/blob/742ed3984f437982057fd46ecfb0bce214563cb8/xarray/core/merge.py#L28

File: xarray/core/common.py (hunk 12 above)
[the remark this answers is not in the document]
Comment (shoyer) [reply xarray/core/common.py]: I think `Mapping[Any, str]` and `Mapping[Hashable, str]` are equivalent -- every mapping key must be hashable.

**Comment by shoyer** [comment]
> @shoyer I changed dimensions from str to Hashable as requested. In my opinion however it's not great, because
> 
> 1. it's currently thoroughly broken due to lack of unit tests
> 2. it weakens type checking a lot, since Tuple is a subclass of Hashable however the vast majority of xarray functions deal with tuples with a specific code branch

I agree it's not great. But some of our APIs are going to be hard to type check regardless, e.g., in cases where we have different behavior for strings vs sequences of strings.

File: xarray/core/utils.py (hunk 9 above)
Comment (crusaderky) [reply xarray/core/utils.py]: Neither mypy nor PyCharm are happy with it.
It has to do with the signature of ``__ior__``:
```
def __ior__(self: MutableSet[T1], other: AbstractSet[T2]) -> MutableSet[Union[T1, T2]]:
    ...
```
When you do ``self |= other``, both PyCharm and mypy understand that you're changing the type of self in place, in other word they treat it to be the same as ``self = self | other``.
Calling ``__ior__`` directly bypasses that. 
This seems to be like a limitation of both tools like in our specific cases we explicitly specified that other is an ``AbstractSet[T1]``. I'll revert to |= and just disable the type checking.

File: xarray/core/utils.py (hunk 8 above)
Comment (crusaderky) [reply xarray/core/utils.py]: same as above

File: xarray/core/utils.py (hunk 10 above)
Comment (crusaderky) [reply xarray/core/utils.py]: fixed

File: xarray/core/utils.py (hunk 9 above)
Comment (shoyer) [reply xarray/core/utils.py]: OK, I'm happy with a comment, too. It's also not a big deal to disable type checking on particular lines when we're sure the overall method/function signature is right.

File: xarray/core/utils.py (hunk 11 above)
Comment (crusaderky) [reply xarray/core/utils.py]: I was going with PEP 484:
> (Note that the return type of __init__ ought to be annotated with -> None. The reason for this is subtle. If __init__ assumed a return annotation of -> None, would that mean that an argument-less, un-annotated __init__ method should still be type-checked? Rather than leaving this ambiguous or introducing an exception to the exception, we simply say that __init__ ought to have a return annotation; the default behavior is thus the same as for other methods.)

but I've now read https://github.com/python/mypy/issues/3358, which likely means a revision of the PEP in the opposite sense is incoming. I'll remove the ``-> None`` from ``__init__``.

**Comment by crusaderky** [comment]
@shoyer implemented all change requests except OrderedDict

File: xarray/core/common.py (hunk 12 above)
[the remark this answers is not in the document]
Comment (crusaderky) [reply xarray/core/common.py]: No, there's absolutely nothing in Mapping saying that the keys must be hashable.

This is perfectly legit, and pretty useful too:
```
class AnyKeyDict(MutableMapping[K, V]):
    def __init__(self, *args: Tuple[K, V], **kwargs: V)::
       self.mapping = {}
       for k, v in args:
           self[k] = v
       for k, v in kwargs.items():
           self[k] = v

    def __setitem__(self, k: K, v: V) -> None:
        try:
            self.mapping[k] = v
        except TypeError:
            self.mapping[pickle.dumps(k)] = v

    ...
```
This can be useful in a few borderline scenarios; for example when de-serialising msgpack data from a non-Python producer, as in msgpack map keys can be anything. Also I'd love to see something like this:
```
class DataArray:
    def __setitem__(self, k, v):
        if isinstance(k, Mapping):
            view = self.sel(**k)
        else:
            view = self.isel(**k)
        view[:] = v
```

File: xarray/core/utils.py (hunk 7 above)
Comment (crusaderky) [reply xarray/core/utils.py]: that would mean that anybody with less than Python 3.7.2 will get errors when running mypy...

Comment (shoyer) [reply xarray/core/utils.py]: Personally, I'm OK with that. But it may be worth clarifying some cohesive policy.

**Comment by shoyer** [comment]
thanks @crusaderky !

File: xarray/core/utils.py (hunk 9 above)
Comment (shoyer) [reply xarray/core/utils.py]: I'm not entirely sure, but It might help to annotate `self` here

File: xarray/core/common.py (hunk 12 above)
[the remark this answers is not in the document]
Comment (shoyer) [reply xarray/core/common.py]: OK, good point.

It turns out we actually do already support this for `DataArray` :)
```
>>> data = xarray.DataArray([0, 0, 0], dims='x')
>>> data[{'x': 1}] = 1
>>> data
<xarray.DataArray (x: 3)>
array([0, 1, 0])
Dimensions without coordinates: x
```
