### ISSUE TITLE
remap_label_indexers removed without deprecation update?

### ISSUE THREAD

**Issue by naught101** [pydata/xarray#7278]
### What is your issue?

Not sure if this is a docs problem or a usage question. Our code was working on v0.19.0, and now isn't, because:

```python
E   ImportError: cannot import name 'remap_label_indexers' from 'xarray.core.indexing' (/home/nedcr/miniconda3/lib/python3.9/site-packages/xarray/core/indexing.py)
```

Seems like this function was removed, but I can't find anything in the changelog on how to replace it, and the commit in which it was removed is huge and impenetrable.

The line we use it in is:

```python
        nearest_point = remap_label_indexers(self.data, dict(x=x, y=y), method='nearest')[0]
```

I realist that this was probably a function intended for internal use only, but it was what I found at the time (years ago).

Is there a better way to do this? What replaces this function?

**Comment by TomNicholas** [comment]
> I realise that this was probably a function intended for internal use only

Yes, everything under `xarray.core` is internal, and unfortunately internal functions aren't publicly supported, so we provide no guarantee that they will still work/exist between versions.

> Is there a better way to do this? What replaces this function?

@benbovy should know!

**Comment by benbovy** [comment]
You may look at the logic implemented in the `map_index_queries()` function in `xarray.core.indexing`. This function is still not public API, but it calls `.sel()` for each index object, which should be more stable (although experimental).

Eventually we'll probably make `merge_sel_results()` public too. It might be useful for third-party indexes.

**Comment by naught101** [comment]
Thank you, this is sufficient for me for now. I was able to replace 

```python
nearest_point = remap_label_indexers(self.data, dict(x=x, y=y), method='nearest')[0]
```

with

```python
nearest_point = map_index_queries(self.data, dict(x=x, y=y), method='nearest').dim_indexers
```

**Comment by benbovy** [comment]
👍 

Use it at your own risk 😉

**Comment by naught101** [comment]
If it takes another couple of years to break, and need another re-write that's probably OK.

But if there is a better/more standard way to do what I'm trying to do, please let me know.

The underlying issue is that I have a netcdf with a RotatedPole grid (e.g. any of the CORDEX data), and I need to find the nearest grid point to a certain point. To do this, I map my point onto the RotatedPole projection (converting it from `lat, lon`, to `x, y`, or `rlat, rlon`), and then use the index mapping's `nearest` method to find the nearest grid point. 

It didn't seem like there was an obvious way to do this with the actual API functions, so that's what I landed on.
