### PR TITLE
CI: python 3.12 by default.

### PR DESCRIPTION
**Pull request by dcherian**
1. Now that numba supports 3.12.
2. Disabled `pint` on the main environment since it doesn't work. Pint is still installed in the `all-but-dask` env, which is still runs python 3.11 for this reason.

### CODE REVIEW

**Comment by dcherian** [comment]
@Illviljan are you able to take a look at these mypy failures?

If not, we can bump the mypy test python version later.

```
xarray/tests/test_typed_ops.py: note: In function "test_dataset_typed_ops":
xarray/tests/test_typed_ops.py:139: error: Argument 1 to "_test" has incompatible type "Variable"; expected "Dataset"  [arg-type]
xarray/tests/test_typed_ops.py:140: error: Argument 1 to "_test" has incompatible type "DataArray"; expected "Dataset"  [arg-type]
xarray/tests/test_typed_ops.py:151: error: Argument 1 to "_test" has incompatible type "Variable"; expected "Dataset"  [arg-type]
xarray/tests/test_typed_ops.py:152: error: Argument 1 to "_test" has incompatible type "DataArray"; expected "Dataset"  [arg-type]
xarray/tests/test_typed_ops.py:163: error: Argument 1 to "_test" has incompatible type "Variable"; expected "Dataset"  [arg-type]
xarray/tests/test_typed_ops.py:164: error: Argument 1 to "_test" has incompatible type "DataArray"; expected "Dataset"  [arg-type]
```

**Review by keewis — APPROVED** [review]
looks good to me, at least as far as the non-typing changes go.

The reason `pint` fails is still the same as in #8605: `pint` didn't define `dtype` explicitly, so `is_duck_array` does not recognize it as a duck array on `python>=3.12`. I guess I should ask for a release of `pint`...

**Comment by dcherian** [comment]
Merging since this really reduces our CI times
